---
title: "Interactivity"
output: html_document
---
Inter activity is great

Here is the package
```{r, message=FALSE}
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

```{r}
data("nyc_airbnb")

nyc_airbnb <-
  nyc_airbnb %>% 
  mutate(
    rating = review_scores_location / 2
  ) %>% 
  select(
    neighbourhood_group, neighbourhood, rating,
    price, room_type, lat, long
  ) %>% 
  filter(
    neighbourhood_group == "Manhattan",
    room_type == "Entire home/apt",
    price <= 500,
    price >= 100
  )
```

Let's make plots
```{r}
nyc_airbnb %>% 
  mutate(
    label = str_c("Price: $", price, "\nRating:", rating)
  ) %>% 
  plot_ly(
    x = ~lat, y = ~long, color = ~price,
    text = ~label,
    type = "scatter", mode = "markers"
  )
```

```{r}
nyc_airbnb %>%
  mutate(
    neighbourhood = fct_reorder(neighbourhood, price)
  ) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~price, color = ~neighbourhood,
    type = "box", colors = "viridis"
  )
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood) %>%
  mutate(
    neighbourhood = fct_reorder(neighbourhood, n)
  ) %>% 
  plot_ly(
    x = ~neighbourhood, y = ~n, 
    type = "bar", color = ~neighbourhood, colors = "viridis"
  )
```

```{r}
scatter_ggplot = 
  nyc_airbnb |>
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.25) +
  coord_cartesian()

ggplotly(scatter_ggplot)
```

